[package]
name = "playtime"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
chrono = "0.4.41"
dirs = "6.0.0"
serde_yaml = "0.9.34+deprecated"
rusqlite = "0.35.0"